apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      # ADD THIS ANNOTATION BLOCK:
      annotations:
        rollout: "update-1" 
    spec:
      containers:
      - name: website
        image: us-central1-docker.pkg.dev/pk-sandbox-507311/pk-repo-v2/pk-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
