apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      annotations:
        rollout: "update-2" 
    spec:
      containers:
      - name: website
        image: us-central1-docker.pkg.dev/pk-sandbox-507311/pk-repo-v2/pk-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # ADD THIS BLOCK:
        resources:
          requests:
            cpu: "100m" # Requests 10% of a single CPU core
          limits:
            cpu: "200m" # Cannot use more than 20% of a single CPU core
